project '/Users/shivuppal/Desktop/fundexpress-back-end/fundExpressApp/fundExpressApp.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'fundExpressApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fundExpressApp
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'fundExpressAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'fundExpressAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
